Experimenting with mobility matrix bounds
----

In [1]:
import numpy as np
from numpy import array

In [9]:
def get_lower_bound(D1,D2):
    global g1,g2,alpha
    g1 = 2*D1/(D1+D2)
    g2 = 2*D2/(D1+D2)
    a = np.sqrt(D1*g1)/20
    b = np.sqrt(D2*g2)
    alpha = np.pi/2 - 1
    f = lambda p1,p2 : p1*(1/g1 - alpha*p2)*a**2 + p2*(1/g2 - alpha*p1)*b**2 - 2*alpha*p1*p2*a*b
    return f

In [2]:
def M(rho_1,rho_2,D1,D2):
    rho = rho_1 + rho_2
    M = np.array([[D1*rho_1*(1-rho)*(1-g1*alpha*rho_2),(D1+D2)*g1*g2*alpha*(1-rho)*rho_1*rho_2/2],[(D1+D2)*g1*g2*alpha*(1-rho)*rho_1*rho_2/2,D2*rho_2*(1-rho)*(1-g2*alpha*rho_1)]])
    return M
    

In [10]:
f = get_lower_bound(1,20)

In [11]:
p1 = np.linspace(0,1,101)
p2 = np.linspace(0,1,101)

In [12]:
eps = 0.02
print(p1[np.argmin(f(p1,1-p1-eps))])
print(np.amin(f(p1,1-p1-eps)))
M(p1[np.argmin(f(p1,1-p1-eps))],1-p1[np.argmin(f(p1,1-p1-eps))]-eps,1,20)

0.9500000000000001
-0.020449208126420364


array([[ 0.01896901,  0.00061972],
       [ 0.00061972, -0.00039443]])

In [13]:
f(.93,.07)

-0.020336612246665497

In [9]:
f = get_lower_bound(1,10)

In [10]:
f(0,p2)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [20]:
M(0.93,0.06,20,1)

array([[ 1.85393325e-01,  6.06674953e-04],
       [ 6.06674953e-04, -6.67495305e-06]])